package entities;
// Generated Aug 6, 2022 11:15:07 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name="Room"
    ,catalog="HotelDB1"
)
public class Room  implements java.io.Serializable {


     private String roomId;
     private String roomName;
     private String category;
     private String type;
     private String status;
     private int price;

    public Room() {
    }

    public Room(String roomId, String roomName, String category, String type, String status, int price) {
       this.roomId = roomId;
       this.roomName = roomName;
       this.category = category;
       this.type = type;
       this.status = status;
       this.price = price;
    }
   
     @Id 

    
    @Column(name="RoomID", unique=true, nullable=false, length=50)
    public String getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    
    @Column(name="RoomName", nullable=false, length=50)
    public String getRoomName() {
        return this.roomName;
    }
    
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    
    @Column(name="Category", nullable=false, length=50)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="Type", nullable=false, length=10)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="Status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="Price", nullable=false)
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }




}


